import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from app.mcp_server.tools import list_registered_tools
from app.orchestration.turn_loop import run_simulation
from app.replay.time_travel import branch_from_session
from app.scenarios.library import list_scenarios
from app.security.scan import (
    scan_product_language,
    scan_repository_for_secrets,
    scan_repository_for_sensitive_data,
)
from app.telemetry.events import telemetry_summary
from app.workspace.config import examples_enabled_for_validation, workspace_status


BACKEND_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = BACKEND_ROOT.parent
VALIDATION_MODULES = (
    ("dynamic_personas", "app.validate_dynamic_personas"),
    ("empty_workspace", "app.validate_empty_workspace"),
    ("workspace_package", "app.validate_workspace_package"),
    ("phase4", "app.validate_phase4"),
    ("phase5", "app.validate_phase5"),
    ("phase7", "app.validate_phase7"),
    ("phase8", "app.validate_phase8"),
    ("phase9", "app.validate_phase9"),
    ("scenario_importer", "app.scenarios.importer"),
    ("evaluation_harness", "app.eval.harness"),
)
REQUIRED_ENDPOINTS = {
    "/health",
    "/scenarios",
    "/scenarios/{scenario_id}",
    "/scenarios/validate",
    "/scenario/run",
    "/scenario/run-custom",
    "/scenario/stream",
    "/scenario/stream-custom",
    "/scenario/sessions",
    "/replay/branch-from",
    "/reports/latest",
    "/manager/fragility-map",
    "/mcp/tools",
    "/voice/status",
    "/eval/report",
    "/telemetry/summary",
    "/workspace/status",
    "/workspace/initialize-empty",
    "/workspace/enable-examples",
    "/workspace/disable-examples",
    "/workspace/apply-template/eduky",
    "/workspace/apply-template/creator-operations",
    "/workspace/apply-template/{template_id}",
    "/workspace/walkthrough",
    "/workspace/configure-organization",
    "/workspace/knowledge",
    "/workspace/roles",
    "/workspace/skills",
    "/workspace/profiles",
    "/workspace/scenarios",
    "/workspace/templates",
    "/workspace/scenario-templates",
}
GENERATED_IGNORE_PROBES = (
    ".env",
    ".venv/release-probe",
    "node_modules/release-probe",
    "backend/app/__pycache__/release-probe.pyc",
    "frontend/.next/release-probe",
    "dist/release-probe",
    "backend/.crisol_sessions/release-probe.json",
    "backend/.crisol_audio/release-probe.mp3",
    "backend/.crisol_telemetry/release-probe.jsonl",
    "backend/.crisol_exports/release-probe.json",
    "backend/app/data/workspace/config/workspace.json",
    "backend/app/data/workspace/scenario_packs/release-probe.json",
    "backend/app/data/workspace/knowledge/release-probe.md",
    "backend/app/data/workspace/roles/release-probe.json",
    "backend/app/data/workspace/skills/release-probe.json",
    "backend/app/data/workspace/profiles/release-probe.json",
)
ATTRIBUTION_PATTERNS = (
    "generated by " + "ai",
    "ai" + "-assisted",
    "ai " + "assisted",
    "chat" + "gpt",
)


def run_release_validation() -> dict[str, Any]:
    checks: list[dict[str, Any]] = []

    for check_id, module in VALIDATION_MODULES:
        checks.append(_run_validation_module(check_id, module))

    checks.extend(
        [
            _endpoint_registry_check(),
            _scenario_library_check(),
            _telemetry_check(),
            _mcp_tools_check(),
            _replay_check(),
            _security_check(),
            _sensitive_data_check(),
            _product_language_check(),
            _attribution_check(),
            _env_protection_check(),
            _generated_ignore_check(),
            _docker_smoke_support_check(),
            _external_integration_check(),
        ]
    )

    blocking_issues = [
        check["summary"] for check in checks if check["status"] == "fail"
    ]
    warnings = [check["summary"] for check in checks if check["status"] == "warn"]
    score = max(0, 100 - len(blocking_issues) * 15 - len(warnings) * 3)
    release_candidate = not blocking_issues and score >= 90
    status = "fail" if blocking_issues else "warn" if warnings else "pass"
    next_steps = [
        check["recommendation"]
        for check in checks
        if check["status"] != "pass" and check.get("recommendation")
    ]
    if not next_steps:
        next_steps = ["Tag the verified release candidate and execute the deployment smoke test."]

    return {
        "status": status,
        "release_candidate": release_candidate,
        "checks": checks,
        "score": score,
        "blocking_issues": blocking_issues,
        "warnings": warnings,
        "recommended_next_steps": next_steps,
    }


def _run_validation_module(check_id: str, module: str) -> dict[str, Any]:
    result = subprocess.run(
        [sys.executable, "-m", module],
        cwd=BACKEND_ROOT,
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )
    output_lines = [
        line.strip()
        for line in (result.stdout + "\n" + result.stderr).splitlines()
        if line.strip()
    ]
    passed = result.returncode == 0
    return _check(
        f"validation_{check_id}",
        "pass" if passed else "fail",
        f"{check_id.replace('_', ' ').title()} validation passed."
        if passed
        else f"{check_id.replace('_', ' ').title()} validation failed.",
        {
            "module": module,
            "return_code": result.returncode,
            "last_output": output_lines[-1] if output_lines else None,
        },
        f"Run python -m {module} and resolve the reported failure." if not passed else None,
    )


def _endpoint_registry_check() -> dict[str, Any]:
    from app.main import app

    registered = {route.path for route in app.routes}
    missing = sorted(REQUIRED_ENDPOINTS - registered)
    return _check(
        "endpoint_registry",
        "pass" if not missing else "fail",
        "Required product endpoints are registered."
        if not missing
        else "Required product endpoints are missing.",
        {"registered_count": len(registered), "missing": missing},
        "Restore every required release endpoint." if missing else None,
    )


def _scenario_library_check() -> dict[str, Any]:
    scenarios = list_scenarios()
    status = workspace_status()
    expected_active = status["scenario_count"] + (
        5 if status["load_examples"] else 0
    )
    valid = len(scenarios) == expected_active and all(
        scenario.get("data_classification") == "sanitized-training"
        for scenario in scenarios
    )
    return _check(
        "scenario_library",
        "pass" if valid else "fail",
        "Scenario Library matches the configured workspace and optional example mode."
        if valid
        else "Scenario Library count or classification does not match workspace status.",
        {
            "active_scenario_count": len(scenarios),
            "workspace_scenario_count": status["scenario_count"],
            "examples_enabled": status["load_examples"],
            "workspace_empty": status["is_empty"],
        },
        "Repair workspace scenario discovery and example-mode configuration."
        if not valid
        else None,
    )


def _telemetry_check() -> dict[str, Any]:
    summary = telemetry_summary()
    valid = (
        summary.get("status") == "active"
        and summary.get("data_mode") == "sanitized-training"
        and summary.get("production_changes") is False
        and summary.get("event_count", 0) > 0
    )
    return _check(
        "telemetry_summary",
        "pass" if valid else "fail",
        "Local telemetry is active and sanitized."
        if valid
        else "Telemetry summary does not meet the release contract.",
        {
            "event_count": summary.get("event_count", 0),
            "data_mode": summary.get("data_mode"),
            "production_changes": summary.get("production_changes"),
        },
        "Run a validation scenario and verify telemetry allowlisting." if not valid else None,
    )


def _mcp_tools_check() -> dict[str, Any]:
    tools = list_registered_tools()
    valid = len(tools) >= 6
    return _check(
        "mcp_tools",
        "pass" if valid else "fail",
        "MCP tool surface contains the required tools."
        if valid
        else "MCP tool surface is incomplete.",
        {"tool_count": len(tools), "tools": [tool["name"] for tool in tools]},
        "Restore the six required CRISOL tools." if not valid else None,
    )


def _replay_check() -> dict[str, Any]:
    with examples_enabled_for_validation():
        session = run_simulation(
            role_id="ROLE-SRE",
            scenario_seed="SCN-SRE-001",
            auto_mode=True,
        )
        node = next(
            item for item in session["timeline"]["nodes"] if item["turn_number"] == 1
        )
        branch = branch_from_session(
            session["session_id"],
            node["node_id"],
            "Freeze writes and identify primary database writer",
        )
    valid = bool(
        branch.get("new_session_id")
        and branch.get("comparison")
        and branch.get("citations")
    )
    return _check(
        "replay_branch",
        "pass" if valid else "fail",
        "Time-Travel Replay produced a cited branch comparison."
        if valid
        else "Time-Travel Replay branch contract failed.",
        {
            "source_session_id": session["session_id"],
            "branch_session_id": branch.get("new_session_id"),
            "citation_count": len(branch.get("citations", [])),
        },
        "Repair deterministic replay branch generation." if not valid else None,
    )


def _security_check() -> dict[str, Any]:
    report = scan_repository_for_secrets(REPOSITORY_ROOT)
    return _check(
        "secret_scan",
        report["status"],
        "Repository credential scan passed."
        if report["status"] == "pass"
        else "Credential-like material was detected.",
        {"finding_count": report["finding_count"], "findings": report["findings"]},
        "Remove and rotate any exposed credentials." if report["findings"] else None,
    )


def _sensitive_data_check() -> dict[str, Any]:
    report = scan_repository_for_sensitive_data(REPOSITORY_ROOT)
    return _check(
        "sensitive_data_scan",
        report["status"],
        "Repository sensitive-data scan passed."
        if report["status"] == "pass"
        else "Sensitive-data-like content was detected.",
        {"finding_count": report["finding_count"], "findings": report["findings"]},
        "Replace sensitive content with sanitized fictional data." if report["findings"] else None,
    )


def _product_language_check() -> dict[str, Any]:
    report = scan_product_language(REPOSITORY_ROOT)
    return _check(
        "product_language",
        report["status"],
        "Frontend product language is release-ready."
        if report["status"] == "pass"
        else "Prohibited product language was detected.",
        {
            "files_scanned": report["files_scanned"],
            "finding_count": report["finding_count"],
            "findings": report["findings"],
        },
        "Replace prohibited frontend language with product terminology."
        if report["findings"]
        else None,
    )


def _attribution_check() -> dict[str, Any]:
    findings = []
    for path in _repository_text_files():
        for line_number, line in enumerate(
            path.read_text(encoding="utf-8", errors="ignore").splitlines(),
            start=1,
        ):
            lower_line = line.lower()
            for pattern in ATTRIBUTION_PATTERNS:
                if pattern in lower_line:
                    findings.append(
                        {
                            "file": path.relative_to(REPOSITORY_ROOT).as_posix(),
                            "line": line_number,
                            "term": pattern,
                        }
                    )
    return _check(
        "attribution_scan",
        "pass" if not findings else "fail",
        "Repository attribution scan passed."
        if not findings
        else "Prohibited attribution language was detected.",
        {"finding_count": len(findings), "findings": findings},
        "Remove prohibited attribution language." if findings else None,
    )


def _env_protection_check() -> dict[str, Any]:
    ignored = _git_check_ignore(".env")
    tracked = (
        subprocess.run(
            ["git", "ls-files", "--error-unmatch", ".env"],
            cwd=REPOSITORY_ROOT,
            capture_output=True,
            text=True,
            check=False,
        ).returncode
        == 0
    )
    valid = ignored and not tracked
    return _check(
        "env_protection",
        "pass" if valid else "fail",
        "The local .env file is ignored and untracked."
        if valid
        else "The local .env file is not safely protected.",
        {"ignored": ignored, "tracked": tracked},
        "Add .env to .gitignore and remove it from the Git index." if not valid else None,
    )


def _generated_ignore_check() -> dict[str, Any]:
    missing = [probe for probe in GENERATED_IGNORE_PROBES if not _git_check_ignore(probe)]
    return _check(
        "generated_folders_gitignore",
        "pass" if not missing else "fail",
        "Generated runtime and build paths are ignored."
        if not missing
        else "Generated paths are missing Git ignore coverage.",
        {"probes": len(GENERATED_IGNORE_PROBES), "missing": missing},
        "Add missing generated paths to .gitignore." if missing else None,
    )


def _docker_smoke_support_check() -> dict[str, Any]:
    artifacts_exist = all(
        path.exists()
        for path in (
            BACKEND_ROOT / "Dockerfile",
            BACKEND_ROOT / ".dockerignore",
            REPOSITORY_ROOT / "docs" / "DOCKER_SMOKE_TEST.md",
        )
    )
    if not artifacts_exist:
        return _check(
            "docker_smoke_support",
            "fail",
            "Docker smoke-test artifacts are incomplete.",
            {"artifacts_exist": False},
            "Restore the backend container files and Docker smoke-test guide.",
        )

    docker = shutil.which("docker")
    if not docker:
        return _check(
            "docker_smoke_support",
            "warn",
            "Docker artifacts are present; the Docker CLI is unavailable for a live smoke check.",
            {"artifacts_exist": True, "docker_cli": False, "daemon": False},
            "Run the documented Docker smoke test on a host with Docker available.",
        )

    result = subprocess.run(
        [docker, "info", "--format", "{{.ServerVersion}}"],
        cwd=REPOSITORY_ROOT,
        capture_output=True,
        text=True,
        timeout=10,
        check=False,
    )
    if result.returncode != 0:
        return _check(
            "docker_smoke_support",
            "warn",
            "Docker artifacts are present; the local Docker daemon is unavailable.",
            {"artifacts_exist": True, "docker_cli": True, "daemon": False},
            "Start Docker and run the documented container smoke test.",
        )
    return _check(
        "docker_smoke_support",
        "pass",
        "Docker artifacts and local daemon are available for smoke testing.",
        {
            "artifacts_exist": True,
            "docker_cli": True,
            "daemon": True,
            "server_version": result.stdout.strip(),
        },
    )


def _external_integration_check() -> dict[str, Any]:
    configured = bool(
        os.getenv("AZURE_AI_PROJECT_ENDPOINT") and os.getenv("AZURE_SEARCH_ENDPOINT")
    )
    return _check(
        "external_integration_readiness",
        "pass" if configured else "warn",
        "Live IQ integration variables are present in the process environment."
        if configured
        else "Live IQ adapters require deployment-environment verification.",
        {"foundry_and_search_configured": configured},
        "Validate Foundry IQ, Fabric IQ, and Work IQ adapters in the target Azure environment."
        if not configured
        else None,
    )


def _git_check_ignore(relative_path: str) -> bool:
    return (
        subprocess.run(
            ["git", "check-ignore", "-q", "--no-index", relative_path],
            cwd=REPOSITORY_ROOT,
            capture_output=True,
            text=True,
            check=False,
        ).returncode
        == 0
    )


def _repository_text_files() -> list[Path]:
    ignored = {
        ".git",
        ".next",
        ".venv",
        "__pycache__",
        "node_modules",
        ".crisol_sessions",
        ".crisol_audio",
        ".crisol_telemetry",
        ".crisol_exports",
    }
    suffixes = {".css", ".js", ".json", ".jsx", ".md", ".py", ".ts", ".tsx", ".txt"}
    return [
        path
        for path in REPOSITORY_ROOT.rglob("*")
        if path.is_file()
        and not path.is_symlink()
        and path.name != ".env"
        and path.suffix.lower() in suffixes
        and not any(part in ignored for part in path.relative_to(REPOSITORY_ROOT).parts)
        and path.stat().st_size <= 2_000_000
    ]


def _check(
    check_id: str,
    status: str,
    summary: str,
    details: dict[str, Any],
    recommendation: str | None = None,
) -> dict[str, Any]:
    return {
        "check_id": check_id,
        "status": status,
        "summary": summary,
        "details": details,
        "recommendation": recommendation,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate the CRISOL release candidate.")
    parser.add_argument("--json", action="store_true", help="Print the complete JSON report.")
    arguments = parser.parse_args()
    report = run_release_validation()

    if arguments.json:
        print(json.dumps(report, indent=2))
    else:
        label = "PASS" if report["release_candidate"] else "FAIL"
        print(f"{label} release validation")
        print(f"score: {report['score']}")
        print(f"blocking_issues: {len(report['blocking_issues'])}")
        print(f"warnings: {len(report['warnings'])}")

    if not report["release_candidate"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
